services:
  fabric-tools:
    build:
      context: .
      dockerfile: Dockerfile.fabric-tools
    platform: linux/arm64
    volumes:
      - ./config/fabric:/etc/hyperledger/fabric
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=waterchain
      - DB_USER=admin
      - DB_PASSWORD=password
    depends_on:
      - postgres
      - fabric-tools

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:4000/api
    depends_on:
      - api

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=waterchain
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus

volumes:
  postgres-data:
  prometheus-data:
  grafana-data: