services:
  fabric-tools:
    build:
      context: .
      dockerfile: Dockerfile.fabric-tools
    platform: linux/arm64
    volumes:
      - ./config/fabric:/etc/hyperledger/fabric
      - ./chaincode:/chaincode
    working_dir: /etc/hyperledger/fabric
    entrypoint: ["sh", "/usr/local/bin/fabric-tools-entrypoint.sh"]
    environment:
      - FABRIC_CFG_PATH=/etc/hyperledger/fabric

  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - /app/backend/node_modules
      - /app/frontend/node_modules
    ports:
      - "4000:4000"  # Backend
      - "4001:4001"  # Frontend
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0  # Permitir acesso externo
      - WDS_SOCKET_HOST=0.0.0.0  # Para o webpack dev server
    develop:
      watch:
        - action: sync+restart
          path: ./backend
          target: /app/backend
          ignore:
            - node_modules/
            - .git/
        - action: sync
          path: ./frontend
          target: /app/frontend
          ignore:
            - node_modules/
            - .git/
            - build/
    depends_on:
      - postgres
      - fabric-tools

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=waterchain
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-dev-data: