services:
  api:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=waterchain
      - DB_USER=admin
      - DB_PASSWORD=password
    depends_on:
      - postgres
      - peer0.org1.waterchain.com
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - api
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - ./config/nginx/default.conf:/etc/nginx/conf.d/default.conf

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=waterchain
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  ca.org1.waterchain.com:
    image: hyperledger/fabric-ca:latest
    platform: linux/arm64
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.org1.waterchain.com
      - FABRIC_CA_SERVER_TLS_ENABLED=false
      - FABRIC_CA_SERVER_PORT=7054
      - FABRIC_CA_SERVER_ADMIN_USER=admin
      - FABRIC_CA_SERVER_ADMIN_PASS=adminpw
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./config/fabric/crypto-config/peerOrganizations/org1.waterchain.com/ca/:/etc/hyperledger/fabric-ca-server
    container_name: ca.org1.waterchain.com

  orderer.waterchain.com:
    image: hyperledger/fabric-orderer:latest
    platform: linux/arm64
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=false
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
      - ./config/fabric/channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./config/fabric/crypto-config/ordererOrganizations/waterchain.com/orderers/orderer.waterchain.com/msp:/var/hyperledger/orderer/msp
      - orderer-data:/var/hyperledger/production/orderer
    ports:
      - "7050:7050"
    container_name: orderer.waterchain.com

  peer0.org1.waterchain.com:
    image: hyperledger/fabric-peer:latest
    platform: linux/arm64
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=waterchain_default
      - CORE_PEER_ID=peer0.org1.waterchain.com
      - CORE_PEER_ADDRESS=peer0.org1.waterchain.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.waterchain.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.waterchain.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.waterchain.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_TLS_ENABLED=false
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
      - /var/run/docker.sock:/host/var/run/docker.sock
      - ./config/fabric/crypto-config/peerOrganizations/org1.waterchain.com/peers/peer0.org1.waterchain.com/msp:/etc/hyperledger/fabric/msp
      - peer0-data:/var/hyperledger/production
    ports:
      - "7051:7051"
      - "7052:7052"
    depends_on:
      - couchdb0
    container_name: peer0.org1.waterchain.com

  couchdb0:
    image: couchdb:3.3.2
    platform: linux/arm64
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports:
      - "5984:5984"
    volumes:
      - couchdb0-data:/opt/couchdb/data
    container_name: couchdb0

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  postgres-data:
  prometheus-data:
  grafana-data:
  ca1-data:
  orderer-data:
  peer0-data:
  couchdb0-data: