OrdererOrgs:
  - Name: Orderer
    Domain: waterchain.com
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: Org1
    Domain: org1.waterchain.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1